# fly.toml app configuration file generated for pitchbot on 2026-04-13T15:26:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pitchbot'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "pitchbot_data"
  destination = "/data"
